package burp;

enum ExtractionOutcome {
    UPDATED,
    GLOBAL_DISABLED,
    TOOL_DISABLED,
    RULE_DISABLED,
    EMPTY_REGEX,
    INVALID_REGEX,
    INVALID_TEMPLATE,
    PATH_MISMATCH,
    QUERY_MISMATCH,
    SERVICE_MISMATCH,
    METHOD_MISMATCH,
    DISCRIMINATOR_MISMATCH,
    LEGACY_REQUEST_MISMATCH,
    AMBIGUOUS_CONTEXT,
    STALE_RESPONSE,
    EMPTY_SOURCE,
    REGEX_NO_MATCH,
    MISSING_CAPTURE_GROUP,
    UNSAFE_REPLAY_DISABLED,
    NO_REFRESH_CANDIDATE,
    REFRESH_FAILED,
    REPLAY_FAILED
}
