package burp;

import java.util.Map;

final class UiText {
    private static final Map<String, String> SPANISH = Map.ofEntries(
            Map.entry("English", "Inglés"),
            Map.entry("Spanish", "Español"),
            Map.entry("Language:", "Idioma:"),
            Map.entry("Configuration...", "Configuración..."),
            Map.entry("Tool Configuration", "Configuración de la herramienta"),
            Map.entry("Assign to Variable...", "Asignar a variable..."),
            Map.entry("Replace variables with their values...", "Sustituir variables por sus valores..."),
            Map.entry("Converts the placeholders in this request to plain-text values.", "Convierte los placeholders de esta petición en valores de texto."),
            Map.entry("Change variable folder...", "Cambiar carpeta de variables..."),
            Map.entry("Replaces matching placeholders from one folder with those from another.", "Sustituye los placeholders coincidentes de una carpeta por los de otra."),
            Map.entry("Replace variables with their values", "Sustituir variables por sus valores"),
            Map.entry("Preview of the values that will be written to the request:", "Vista previa de los valores que se escribirán en la petición:"),
            Map.entry("Replace values", "Sustituir valores"),
            Map.entry("Cancel", "Cancelar"),
            Map.entry("No defined variables can be replaced.\n", "No hay variables definidas que se puedan sustituir.\n"),
            Map.entry("The following will be replaced:\n", "Se sustituirán:\n"),
            Map.entry("(empty value)", "(valor vacío)"),
            Map.entry("\nThe following will be kept because they are not defined:\n", "\nSe conservarán porque no están definidas:\n"),
            Map.entry("\nThis action modifies the template open in Repeater.", "\nEsta acción modifica la plantilla abierta en Repeater."),
            Map.entry("The request does not contain placeholders with folders.", "La petición no contiene placeholders con carpeta."),
            Map.entry("Change variable folder", "Cambiar carpeta de variables"),
            Map.entry("Apply change", "Aplicar cambio"),
            Map.entry("Source folder:", "Carpeta origen:"),
            Map.entry("Target folder:", "Carpeta destino:"),
            Map.entry("No other folder is available as a target.", "No hay otra carpeta disponible como destino."),
            Map.entry("Select different source and target folders.", "Selecciona carpetas de origen y destino diferentes."),
            Map.entry("No changes", "Sin cambios"),
            Map.entry("There are no matching variables to replace.", "No hay variables coincidentes para sustituir."),
            Map.entry("Preview:", "Vista previa:"),
            Map.entry("There are no matching variables between these folders.", "No hay variables coincidentes entre estas carpetas."),
            Map.entry("\nThe following will be kept because they do not exist in the target folder:\n", "\nSe conservarán porque no existen en la carpeta destino:\n"),
            Map.entry("Assign to Variable", "Asignar a variable"),
            Map.entry("Folder:", "Carpeta:"),
            Map.entry("Search or create a folder", "Buscar o crear una carpeta"),
            Map.entry("Type to filter folders. If the name does not exist, create it here.", "Escribe para filtrar carpetas. Si el nombre no existe, créala aquí."),
            Map.entry("Create folder", "Crear carpeta"),
            Map.entry("The folder does not exist. Create it now?", "La carpeta no existe. ¿Quieres crearla ahora?"),
            Map.entry("Ungrouped", "Sin carpeta"),
            Map.entry("Variable Name:", "Nombre de variable:"),
            Map.entry("Selected Value:", "Valor seleccionado:"),
            Map.entry("Match URL/Path (Regex):", "Coincidir URL/ruta (regex):"),
            Map.entry("Path (literal; query ignored):", "Ruta (literal; se ignora la query):"),
            Map.entry("Extract From:", "Extraer de:"),
            Map.entry("Response Body", "Cuerpo de respuesta"),
            Map.entry("Response Headers", "Cabeceras de respuesta"),
            Map.entry("Request Body", "Cuerpo de petición"),
            Map.entry("Request Headers", "Cabeceras de petición"),
            Map.entry("Regex Pattern (1 group):", "Patrón regex (1 grupo):"),
            Map.entry("The extraction regex must be valid and contain at least one capture group.", "La regex de extracción debe ser válida y contener al menos un grupo de captura."),
            Map.entry("Automatic refresh requires a saved request.", "La actualización automática requiere una petición guardada."),
            Map.entry("Explicit matching requires method, service, port, and path.", "La coincidencia explícita requiere método, servicio, puerto y ruta."),
            Map.entry("The path regular expression is invalid.", "La expresión regular de la ruta no es válida."),
            Map.entry("The query regular expression is invalid.", "La expresión regular de la query no es válida."),
            Map.entry("The request discriminator regular expression is invalid.", "La expresión regular del discriminador de petición no es válida."),
            Map.entry("Save this request to refresh token in the future", "Guardar esta petición para actualizar el token en el futuro"),
            Map.entry("Save Rule", "Guardar regla"),
            Map.entry("Please select or type a variable name.", "Selecciona o escribe un nombre de variable."),
            Map.entry("Variable names cannot contain '.'. Choose the folder separately.", "Los nombres de variable no pueden contener '.'. Elige la carpeta por separado."),
            Map.entry("The variable \"%s\" already exists in this folder. Updating will replace its current value and automation rule.", "La variable «%s» ya existe en esta carpeta. Al actualizarla se sustituirán su valor actual y su regla de automatización."),
            Map.entry("Variable already exists", "La variable ya existe"),
            Map.entry("Update existing variable", "Actualizar variable existente"),
            Map.entry("Create with another name", "Crear con otro nombre"),
            Map.entry("New variable name:", "Nombre de la nueva variable:"),
            Map.entry("Create new variable", "Crear nueva variable"),
            Map.entry("Invalid selection range.", "Rango de selección no válido."),
            Map.entry("Error", "Error"),
            Map.entry("Enable Variable Replacement", "Activar sustitución de variables"),
            Map.entry("Extract variable values from matching responses", "Extraer valores de variables de respuestas coincidentes"),
            Map.entry("Recover expired sessions and retry requests", "Recuperar sesiones caducadas y reintentar peticiones"),
            Map.entry("Updates enabled variables when a response matches their extraction rule. It does not retry the request.", "Actualiza las variables habilitadas cuando una respuesta coincide con su regla de extracción. No reintenta la petición."),
            Map.entry("After a configured status code, runs the saved refresh request and retries the original request. Requires refresh to be enabled for the variable.", "Tras un código de estado configurado, ejecuta la petición de actualización guardada y reintenta la petición original. Requiere activar la actualización para la variable."),
            Map.entry("Recovery trigger status codes:", "Códigos de estado que activan la recuperación:"),
            Map.entry("HTTP status codes (comma separated) that trigger an automatic token refresh (e.g., 401, 403).", "Códigos de estado HTTP (separados por comas) que activan una actualización automática del token (p. ej., 401, 403)."),
            Map.entry("Configure the interface language and the optional tag that uniquely identifies variable placeholders.", "Configura el idioma de la interfaz y la etiqueta opcional que identifica los placeholders de variables."),
            Map.entry("Drag to reorder or move variables between folders.", "Arrastra para reordenar o mover variables entre carpetas."),
            Map.entry("Search folders or variables", "Buscar carpetas o variables"),
            Map.entry("New Folder", "Nueva carpeta"),
            Map.entry("New Variable", "Nueva variable"),
            Map.entry("Delete Selected", "Eliminar selección"),
            Map.entry("More...", "Más..."),
            Map.entry("Clear All", "Borrar todo"),
            Map.entry("Are you sure you want to clear all variables?", "¿Seguro que quieres borrar todas las variables?"),
            Map.entry("Confirm Clear", "Confirmar borrado"),
            Map.entry("Variable Value Editor (Paste long values here)", "Editor de valor de variable (pega aquí valores largos)"),
            Map.entry("Current value", "Valor actual"),
            Map.entry("Changes are saved automatically.", "Los cambios se guardan automáticamente."),
            Map.entry("Variable automation", "Automatización de la variable"),
            Map.entry("Update this variable from matching responses", "Actualizar esta variable desde respuestas coincidentes"),
            Map.entry("Matching responses update the value passively; no request is retried.", "Las respuestas coincidentes actualizan el valor de forma pasiva; no se reintenta ninguna petición."),
            Map.entry("Requires global response extraction and extraction for the current Burp tool to be enabled.", "Requiere activar globalmente la extracción de respuestas y habilitarla para la herramienta actual de Burp."),
            Map.entry("Use this variable for expired-session recovery", "Usar esta variable para recuperar sesiones caducadas"),
            Map.entry("After a configured status, the saved request obtains a new value and the original request is retried.", "Tras un código configurado, la petición guardada obtiene un valor nuevo y se reintenta la petición original."),
            Map.entry("Requires global session recovery, recovery for the current Burp tool, and a saved refresh request.", "Requiere activar globalmente la recuperación de sesión, habilitarla para la herramienta actual de Burp y guardar una petición de actualización."),
            Map.entry("Response extraction is disabled globally. Enable it now?", "La extracción de respuestas está desactivada globalmente. ¿Quieres activarla ahora?"),
            Map.entry("Enable global response extraction", "Activar extracción global de respuestas"),
            Map.entry("Session recovery is disabled globally. Enable it now?", "La recuperación de sesión está desactivada globalmente. ¿Quieres activarla ahora?"),
            Map.entry("Enable global session recovery", "Activar recuperación global de sesión"),
            Map.entry("Session recovery retry safety", "Seguridad del reintento de recuperación"),
            Map.entry("In session recovery, allow retrying non-idempotent requests", "En la recuperación de sesión, permitir reintentar peticiones no idempotentes"),
            Map.entry("Allows retrying methods such as POST, PUT, PATCH, and DELETE after refreshing the value. Enable only when repeating the operation is safe.", "Permite reintentar métodos como POST, PUT, PATCH y DELETE después de actualizar el valor. Actívalo solo cuando sea seguro repetir la operación."),
            Map.entry("Passive extraction request matching", "Coincidencia de peticiones para extracción pasiva"),
            Map.entry("Every configured filter must match. The path does not include the query string.", "Todos los filtros configurados deben coincidir. La ruta no incluye la query."),
            Map.entry("An empty query and a None discriminator do not filter requests.", "Una query vacía y un discriminador Ninguno no filtran peticiones."),
            Map.entry("Literal requires an exact match; a regular expression only needs to find a match.", "Literal exige una coincidencia exacta; una expresión regular solo necesita encontrar una coincidencia."),
            Map.entry("Matching mode:", "Modo de coincidencia:"),
            Map.entry("Explicit filters", "Filtros explícitos"),
            Map.entry("Legacy exact saved request matching", "Coincidencia exacta legacy con la petición guardada"),
            Map.entry("Legacy path regex matching", "Coincidencia legacy mediante regex de ruta"),
            Map.entry("Convert to explicit filters", "Convertir a filtros explícitos"),
            Map.entry("Method:", "Método:"),
            Map.entry("Service:", "Servicio:"),
            Map.entry("Path filter:", "Filtro de ruta:"),
            Map.entry("Query filter:", "Filtro de query:"),
            Map.entry("Request discriminator:", "Discriminador de petición:"),
            Map.entry("The HTTP method must match exactly, ignoring letter case.", "El método HTTP debe coincidir exactamente, sin distinguir mayúsculas de minúsculas."),
            Map.entry("Host, port, and HTTP or HTTPS must all match exactly.", "El host, el puerto y el uso de HTTP o HTTPS deben coincidir exactamente."),
            Map.entry("Matches only the path, without query parameters. Literal compares the full path; a regular expression searches for a match.", "Compara solo la ruta, sin parámetros de query. Literal compara la ruta completa; una expresión regular busca una coincidencia."),
            Map.entry("Optional. Matches the complete raw query string. Leave empty to accept any query.", "Opcional. Compara la query completa sin procesar. Déjala vacía para aceptar cualquier query."),
            Map.entry("Optional. A regular expression must match the selected request body or headers. Use it to distinguish requests to the same endpoint.", "Opcional. Una expresión regular debe coincidir con el cuerpo o las cabeceras seleccionadas. Úsalo para distinguir peticiones al mismo endpoint."),
            Map.entry("Literal", "Literal"),
            Map.entry("Regular expression", "Expresión regular"),
            Map.entry("None", "Ninguno"),
            Map.entry("Regex (with 1 capture group):", "Regex (con 1 grupo de captura):"),
            Map.entry("Update Rule from Response...", "Actualizar regla desde respuesta..."),
            Map.entry("Token Refresh Request", "Petición de actualización del token"),
            Map.entry("Saved Request: None", "Petición guardada: Ninguna"),
            Map.entry("Refresh Variable", "Actualizar variable"),
            Map.entry("Send to Repeater", "Enviar a Repeater"),
            Map.entry("Edit Request", "Editar petición"),
            Map.entry("Use a tag in variable placeholders", "Usar una etiqueta en los placeholders de variables"),
            Map.entry("Enable auto-extraction diagnostic logs", "Activar logs de diagnóstico de extracción automática"),
            Map.entry("General", "General"),
            Map.entry("Automation", "Automatización"),
            Map.entry("Value", "Valor"),
            Map.entry("Variable replacement tools", "Herramientas con sustitución de variables"),
            Map.entry("Automation tool scope", "Ámbito de herramientas para automatización"),
            Map.entry("Tool", "Herramienta"),
            Map.entry("Response extraction", "Extracción de respuestas"),
            Map.entry("Session recovery", "Recuperación de sesión"),
            Map.entry("The tag must start with a letter and contain only letters, numbers, _ or -. ", "La etiqueta debe comenzar por una letra y contener solo letras, números, _ o -. "),
            Map.entry("Example: ", "Ejemplo: "),
            Map.entry("Tag:", "Etiqueta:"),
            Map.entry("Existing requests are not rewritten automatically. When tagging is enabled,", "Las peticiones existentes no se reescriben automáticamente. Al activar las etiquetas,"),
            Map.entry("only placeholders containing the configured tag are replaced.", "solo se sustituyen los placeholders que contienen la etiqueta configurada."),
            Map.entry("The tag must start with a letter and contain only letters, numbers, _ or -.", "La etiqueta debe comenzar por una letra y contener solo letras, números, _ o -."),
            Map.entry("Invalid Tag", "Etiqueta no válida"),
            Map.entry("Select a variable inside this folder to edit its details.", "Selecciona una variable de esta carpeta para editar sus detalles."),
            Map.entry("Select a variable to edit its details.", "Selecciona una variable para editar sus detalles."),
            Map.entry("Select a variable", "Selecciona una variable"),
            Map.entry("Choose a variable on the left to edit its value or configure automation.", "Elige una variable de la izquierda para editar su valor o configurar la automatización."),
            Map.entry("Show advanced automation options", "Mostrar opciones avanzadas de automatización"),
            Map.entry("Hide advanced automation options", "Ocultar opciones avanzadas de automatización"),
            Map.entry("Configure passive-extraction matching and session-recovery retry safety.", "Configura la coincidencia de la extracción pasiva y la seguridad del reintento de recuperación."),
            Map.entry("Replacement paused", "Sustitución pausada"),
            Map.entry("No tools selected", "Ninguna herramienta seleccionada"),
            Map.entry("Active in: ", "Activa en: "),
            Map.entry("Extraction", "Extracción"),
            Map.entry("Recovery", "Recuperación"),
            Map.entry("On", "Activa"),
            Map.entry("Off", "Inactiva"),
            Map.entry("Open configuration to change automation behavior and tool scope.", "Abre la configuración para cambiar la automatización y su ámbito de herramientas."),
            Map.entry("Saved Request: Error parsing request data", "Petición guardada: Error al analizar los datos"),
            Map.entry("Double-click a variable to insert:", "Haz doble clic en una variable para insertarla:"),
            Map.entry("Search variables", "Buscar variables"),
            Map.entry("Double-click to expand or collapse", "Haz doble clic para expandir o contraer"),
            Map.entry("No value", "Sin valor"),
            Map.entry("Insert", "Insertar"),
            Map.entry("Refresh", "Actualizar"),
            Map.entry("Rename", "Renombrar"),
            Map.entry("Copy Placeholder", "Copiar placeholder"),
            Map.entry("Move to...", "Mover a..."),
            Map.entry("Delete", "Eliminar"),
            Map.entry("Variable Name", "Nombre de variable"),
            Map.entry("Current Value", "Valor actual"),
            Map.entry("Auto Extract?", "¿Extracción automática?"),
            Map.entry("Yes", "Sí"),
            Map.entry("No", "No"),
            Map.entry("Failed to send request to Repeater: ", "No se pudo enviar la petición a Repeater: "),
            Map.entry("Edit Saved Request - ", "Editar petición guardada - "),
            Map.entry("Host:", "Host:"),
            Map.entry("Port:", "Puerto:"),
            Map.entry("Save Changes", "Guardar cambios"),
            Map.entry("Copy to Clipboard", "Copiar al portapapeles"),
            Map.entry("Request copied to clipboard.", "Petición copiada al portapapeles."),
            Map.entry("Copied", "Copiado"),
            Map.entry("Failed to copy to clipboard: ", "No se pudo copiar al portapapeles: "),
            Map.entry("Invalid port number.", "Número de puerto no válido."),
            Map.entry("Host cannot be empty.", "El host no puede estar vacío."),
            Map.entry("Failed to parse HTTP request. Please verify the format.", "No se pudo analizar la petición HTTP. Comprueba el formato."),
            Map.entry("Fetching Response...", "Obteniendo respuesta..."),
            Map.entry("Failed to get response from server.", "No se pudo obtener una respuesta del servidor."),
            Map.entry("Fetch Error", "Error de obtención"),
            Map.entry("Error fetching response: ", "Error al obtener la respuesta: "),
            Map.entry("Highlight New Token - ", "Seleccionar nuevo token - "),
            Map.entry("Highlight/select the text you want to extract from the response below. The regex will be auto-generated.", "Selecciona el texto que quieres extraer de la respuesta. El regex se generará automáticamente."),
            Map.entry("Proposed Regex:", "Regex propuesto:"),
            Map.entry("Save Extraction Rule", "Guardar regla de extracción"),
            Map.entry("Please select some text to generate a regex.", "Selecciona algún texto para generar un regex."),
            Map.entry("Extraction rule updated successfully for variable: ", "Regla de extracción actualizada para la variable: "),
            Map.entry("Rule Updated", "Regla actualizada"),
            Map.entry("Refreshing...", "Actualizando..."),
            Map.entry("Refresh Success", "Actualización correcta"),
            Map.entry("Error during refresh: ", "Error durante la actualización: "),
            Map.entry("Refresh Error", "Error de actualización"),
            Map.entry("Folder", "Carpeta"),
            Map.entry("Variable", "Variable"),
            Map.entry("Invalid Name", "Nombre no válido"),
            Map.entry("Folder name:", "Nombre de carpeta:"),
            Map.entry("Variable name:", "Nombre de variable:"),
            Map.entry("A folder with this name already exists.", "Ya existe una carpeta con este nombre."),
            Map.entry("Duplicate Folder", "Carpeta duplicada"),
            Map.entry("Duplicate Variable", "Variable duplicada"),
            Map.entry("The placeholder could not be copied to the system clipboard.", "No se pudo copiar el placeholder al portapapeles del sistema."),
            Map.entry("Create another folder before moving this variable.", "Crea otra carpeta antes de mover esta variable."),
            Map.entry("Move Variable", "Mover variable"),
            Map.entry("Move variable to:", "Mover variable a:"),
            Map.entry("Rename Variable", "Renombrar variable"),
            Map.entry("Rename Folder", "Renombrar carpeta"),
            Map.entry("Delete Variable", "Eliminar variable"),
            Map.entry("Delete Folder", "Eliminar carpeta"),
            Map.entry("Move variables to Ungrouped", "Mover variables a Sin carpeta"),
            Map.entry("Delete folder and variables", "Eliminar carpeta y variables"),
            Map.entry("The following placeholders will change:\n", "Los siguientes placeholders cambiarán:\n"),
            Map.entry(" name cannot be empty.", " no puede tener un nombre vacío."),
            Map.entry(" names cannot contain '.'.", " no puede contener '.' en el nombre."),
            Map.entry("Variable '", "La variable '"),
            Map.entry("' already exists.", "' ya existe."),
            Map.entry("Copied ", "Copiado "),
            Map.entry(" to the clipboard.", " al portapapeles."),
            Map.entry("Placeholder will change:\n", "El placeholder cambiará:\n"),
            Map.entry("Renaming would conflict with '", "El nuevo nombre entraría en conflicto con '"),
            Map.entry("Delete variable '", "¿Eliminar la variable '"),
            Map.entry("Folder contains ", "La carpeta contiene "),
            Map.entry(" variables.", " variables."),
            Map.entry("Cannot move: '", "No se puede mover: '"),
            Map.entry("' already exists in Ungrouped.", "' ya existe en Sin carpeta."),
            Map.entry("Variable refreshed successfully: ", "Variable actualizada correctamente: ")
    );

    private UiText() {}

    static String get(UiLanguage language, String englishText) {
        return language == UiLanguage.SPANISH ? SPANISH.getOrDefault(englishText, englishText) : englishText;
    }
}
